In [1]:
import matplotlib
matplotlib.use("tkagg")
import matplotlib.pyplot
import numpy

import os
import json


In [2]:
def f(x):
    if x > 1: return 3/4*(1-x)**2-2*(1-x)
    elif x < -1: return 3/4*(1+x)**2-2*(1+x)
    else: return x**2-1

In [4]:
x = numpy.linspace(-100.5, 100.5, 1000)
fv = numpy.vectorize(f)(x)
matplotlib.pyplot.plot(x, fv)

# F = numpy.zeros([1000])
# for i, x_i in enumerate(x):
#     F[i] = f(x_i)
# # x = numpy.linspace(-1.5, 1.5, 1000)
# matplotlib.pyplot.plot(x, F)
#
# x = numpy.linspace(-1.5, 1.5, 1000)
# matplotlib.pyplot.plot(x, fv)
matplotlib.pyplot.show()

In [14]:
import utils
utils.generate_plots(["logdir_mlp/logdir_relu", "logdir_mlp/logdir_sigmoid", "logdir_mlp/logdir_tanh"], ["relu", "sigmoid", "tanh"], "logdir_mlp")

In [18]:
import utils
# logdir_resnet18 lr
utils.generate_plots(["logdir_resnet18/logdir_" + str(P) for P in ["0.1", "0.01", "0.001", "0.0001", "0.00001"]], ["lr="+str(P) for P in ["0.1", "0.01", "0.001", "0.0001", "0.00001"]], "logdir_resnet18")


In [ ]:
import utils
# logdir_mlpmixer patch size
utils.generate_plots(["logdir_mlpmixer/logdir_" + str(P) for P in [2, 4, 8, 16, 32]], [str(P)+"x"+str(P) for P in [2, 4, 8, 16, 32]], "logdir_mlpmixer")


In [38]:
def loads_timesjson(list_of_dirs, legend_names, save_path):
    """ Generate plots according to log
    :param list_of_dirs: List of paths to log directories
    :param legend_names: List of legend names
    :param save_path: Path to save the figs
    """
    assert len(list_of_dirs) == len(legend_names), "Names and log directories must have same length"
    data = {}
    for logdir, name in zip(list_of_dirs, legend_names):
        json_path = os.path.join(logdir, 'results.json')
        assert os.path.exists(os.path.join(logdir, 'results.json')), f"No json file in {logdir}"
        with open(json_path, 'r') as f:
            data[name] = json.load(f)

    fig, ax = matplotlib.pyplot.subplots()
    ax.set_xticks([0,1,2,3,4,5], labels=["1x1", "2x2", "4x4", "8x8", "16x16", "32x32"])
    D = []
    for k, yaxis in enumerate(["train_times", "valid_times"]):
        D.append([])
        for i, name in enumerate(data):
            D[k].append(numpy.mean(data[name][yaxis]))

    ax.semilogy(D[0], marker=".", label="train_times", color="C"+str(0))
    ax.semilogy(D[1], marker=".", label="valid_times", color="C"+str(1))
    ax.legend()
    ax.set_xlabel('patch size')
    ax.set_ylabel("time (s)")
    fig.savefig(os.path.join(save_path, f'{yaxis}.png'))

loads_timesjson(["logdir_mlpmixer/logdir_" + str(P) for P in [1, 2, 4, 8, 16, 32]], [str(P)+"x"+str(P) for P in [1, 2, 4, 8, 16, 32]], "logdir_mlpmixer")


In [4]:
def load_jsons(list_of_dirs, legend_names, save_path):
    """ Generate plots according to log
    :param list_of_dirs: List of paths to log directories
    :param legend_names: List of legend names
    :param save_path: Path to save the figs
    """
    assert len(list_of_dirs) == len(legend_names), "Names and log directories must have same length"
    data = {}
    for logdir, name in zip(list_of_dirs, legend_names):
        json_path = os.path.join(logdir, 'results.json')
        assert os.path.exists(os.path.join(logdir, 'results.json')), f"No json file in {logdir}"
        with open(json_path, 'r') as f:
            data[name] = json.load(f)
    D = []
    for k, yaxis in enumerate(["valid_accs"]):
        for i, name in enumerate(data):
            D.append(numpy.max(data[name][yaxis]))

    print(numpy.around(numpy.array(D), decimals=3))

load_jsons(["logdir_mlpmixer/logdir_bs" + str(P) for P in [128, 256, 512, 1024]], ["bs"+str(P) for P in [128, 256, 512, 1024]], "logdir_mlpmixer")
load_jsons(["logdir_mlpmixer/logdir_lr" + str(P) for P in ["0.1", "0.01", "0.001", "0.0001", "0.00001"]], ["lr"+str(P) for P in ["0.1", "0.01", "0.001", "0.0001", "0.00001"]], "logdir_mlpmixer")
load_jsons(["logdir_mlpmixer/logdir_wd" + str(P) for P in ["0.05", "0.005", "0.0005", "0.00005", "0.000005"]], ["wd"+str(P) for P in ["0.05", "0.005", "0.0005", "0.00005", "0.000005"]], "logdir_mlpmixer")
load_jsons(["logdir_mlpmixer/logdir_" + str(P) for P in ["adam", "adamw", "sgd", "momentum"]], [str(P) for P in ["adam", "adamw", "sgd", "momentum"]], "logdir_mlpmixer")
load_jsons(["logdir_mlpmixer/logdir_C" + str(P) for P in [32,64,128,256,512,1024]], ["C"+str(P) for P in [32,64,128,256,512,1024]], "logdir_mlpmixer")
# bs=128, lr=0.001, wd=?, op=adam


[0.856 0.854 0.811 0.764]
[0.649 0.717 0.861 0.721 0.523]
[0.857 0.856 0.856 0.856 0.856]
[0.861 0.856 0.314 0.563]
[0.695 0.754 0.824 0.861 0.872 0.83 ]


In [46]:
load_jsons(["logdir_resnet18/logdir_bs" + str(P) for P in [128, 256, 512, 1024]], ["bs"+str(P) for P in [128, 256, 512, 1024]], "logdir_resnet18")
# print()
load_jsons(["logdir_resnet18/logdir_" + str(P) for P in ["0.1", "0.01", "0.001", "0.0001", "0.00001"]], ["lr"+str(P) for P in ["0.1", "0.01", "0.001", "0.0001", "0.00001"]], "logdir_resnet18")
# print()
load_jsons(["logdir_resnet18/logdir_w" + str(P) for P in ["0.05", "0.005", "0.0005", "0.00005", "0.000005"]], ["wd"+str(P) for P in ["0.05", "0.005", "0.0005", "0.00005", "0.000005"]], "logdir_resnet18")
# print()
load_jsons(["logdir_resnet18/logdir_" + str(P) for P in ["adam", "adamw", "sgd", "momentum"]], [str(P) for P in ["adam", "adamw", "sgd", "momentum"]], "logdir_resnet18")

# bs=128, lr=0.001, wd=0.005, op=adamw

[0.93144531 0.91700368 0.92920121 0.90645568]
[0.77871094 0.91425781 0.92929688 0.92519531 0.778125  ]
[0.93808594 0.93808594 0.921875   0.93300781 0.92851563]
[0.93105469 0.9328125  0.71054688 0.91621094]
